[workspace]
resolver = "2"
members = [
    "newslab-serde",
    "newslab-serde-common",
    "newslab-serde-measurements",
    "newslab-serde-nalgebra",
    "newslab-serde-cv",
    "newslab-serde-num",
]
